version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./internal/stubs:/app/internal/stubs 
    command: ["./app"]
    networks:
      - vendepass-vp

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: ["./api"]
    networks:
      - vendepass-vp
    depends_on:
      - app
  ui:
    build:
      context: ./ui
    ports:
      - "5173:5173"
    networks:
      - vendepass-vp
    depends_on:
      - api

networks:
  vendepass-vp:
    driver: bridge
